version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        ports:
            - "9000:9000"

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql-data:/var/lib/mysql/
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8080:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data:
        driver: local
